#ifndef CPP_VIGENERE_DECRYPTOR_TEST_DATA_H
#define CPP_VIGENERE_DECRYPTOR_TEST_DATA_H

namespace test_data {
    constexpr inline auto big_text = "there are seven days of the week, or uniquely named 24-hour periods designed to provide scheduling context and make time more easily measureable. each of these days is identifiable by specific plans, moods, and tones."
                                     "monday is viewed by many to be the worst day of the week, as it marks the return to work following the weekend, when most full-time employees are given two days off. most students attend school in the morning and return home in the afternoon (usually from about eight until three or seven until two), and most workers go to work in the morning and return home in the evening (usually from nine to five or eight to four)."
                                     "tuesday is the second day of the week, and is in many ways similar to monday. not a whole lot of changes, schedule-wise, between tuesday and monday; most individuals go to school or work and return home to watch television, play video games, make plans with friends, spend time with family, read, or engage in a similar leisure-related activity."
                                     "wednesday is the third day of the week, and serves as the middle of the work week; some individuals refer to wednesday as hump day, as once its workday is complete, employees will have passed the work-week hump, and will be on the downturn, as only two days on the job will remain in the week."
                                     "thursday is the fourth day of the week, and is viewed favorably by many, as it's rather close to the end of the work week."
                                     "friday is the fifth day of the week, and marks the end of the workweek and school-week for the vast majority of employees and students. by friday afternoon evening, most students workers cannot wait to leave and go home, as they won't have to report back to school/work until monday."
                                     "saturday is perhaps the most highly regarded day of the week. because sunday follows it (and there is presumably no work or school to attend, for most individuals), everyone is free to stay out (or awake) until late at night, having fun with plans or other leisure-related activities. to be sure, saturday is generally thought of as a day to partake in hobbies that couldn't otherwise be enjoyed during the regular week.";


    constexpr inline auto encrypted_big_text = "vycgx izg jckxv lcpq dy bpg nctd, wz wegfnmta eybxl 24-pqlp exzqquq sxaqiecs mw xtftxwm aeycsntqpx adgbmzk ycw uimv rxfm uqic ttaqnp kttactvyqem. mctf dy bpgjc stga kj gsxvbkwgputm dp qexkqhza eeivu, dmdwa, ipu rdgma."
                                               "oflstg qu mgtpml dp kpgg bq sc iam eqiqi wig qw rwx emgb, yh bb uciih mpm tvrjkv bq nmgd nwncmlbvo vyc lxmsgeb, lamv ofqi yctn-kgbx murcmnxma cic vbdmp kud wigu fdu. fwav jrjwmvvj yimmvf jawhwt ke rwx uwtegcz ivf icinzv jfkt bv bjv yummzpfmc (nacccjn yzwo rzdnb mkxfi nvbkc rwkmm qi qtomv werxe beq), rls fwav nmgdmzu xm ih ewtb gc mpm ofpcbvo ceb gxbcte fdfm qp kft xdmpzlv (nacccjn yzwo egcx bw hztt hz mkxfi mw nqlp)."
                                               "inmafrw xl bpg jcrhvl frw dy bpg nctd, ivf zq xg uipp upra akdgatz bq dmcwig. pfr p ppwnv jdm wn eyyczma, utftwctg-nghx, jmvnctg bcgjbpr ivf dmcwig; ofqi bvlkmgsnitu xm ih akjfma hz eqii pgl zgksgg pwov rd pibey rtemdkjgdg, xtcp txwmw irktl, uimv natva yzrw yzqgebh, lxmpu rxfm ekkf utuqnp, pttl, wt vlvtom ke y hbuqnrp axqawic-gxtivvb pvbqxzrn."
                                               "pmlpvqstg qu kft mpqtu bpr wn vyc lxms, ceb hxzdgj yh mpm ozbsem wh kft pwzm nctd; awov gcwqdkuspea zgwcg mw egultllia rq wnux frw, pl wvev gil ewtbbpr qa efkeembg, vkeewggvq lbtt jrtt iiauvb iam eqii-lxms jlke, tvl yzja um wp kft wwepksgg, ia qejn mew frwh hv bjv hdu eqnc ptfiqp zl iam egvi."
                                               "iaczuuyn ba bjv ddnzbj uyn hn bjv utxs, ipu gh oqmyvb utdwtrzar jg orln, ta qv'j ppmpmt tjdlm bq kft xvl qw rwx ewtb utxs."
                                               "ntzbpr qa vyc ubnbj uyn hn bjv utxs, ipu kpksa vyc tgl wh kft pwzmnctd ivf jawhwt-yvcz ywz vyc ktab orhdkqba fd tfxtqpctl ivf jrjwmvvj. zn yzqfrw pybmtemdg mdgegcz, uwuk qinlmpkq lhzsgiq rtvvqk upbb bq ccpom ipu ed awug, rq iamg yfl'i aidg km gxxwtk zpvs bq jawhwt/yfpz nvbkc kdglia."
                                               "jyinzlcp gh imzjrnh mpm ofqi aqojcw gxoitucs wig qw rwx emgb. ztvicuv qjglia wmaeweu zr (pgl bjvpt ba xtvqjfijnp ld pwzm fp hvpwqc rd tbbgeb, uhz uqjr xglqxzbjtta), gmcgrwvg zq ukmm vf qitg wwk (mg teimv) scmqt nrrt tb vkxfi, aidkee unv ekkf eeivu fp dmpmt ccxlczg-icatbmf raibdqvzch. mw jg jsgx, aivlpstg qu xccxzincw iawciyr dy ia c uyn mw xcirpdm qp ymquqmu kfpm kwwcbc'm wbjvplbam dv cccwggu bjkqvi kft kmowcyg pmmm.";
}// namespace test_data

#endif//CPP_VIGENERE_DECRYPTOR_TEST_DATA_H
